set_property PACKAGE_PIN U16 [get_ports tx]
set_property PACKAGE_PIN W5  [get_ports st]
set_property PACKAGE_PIN U18 [get_ports rx]
set_property PACKAGE_PIN B18 [get_ports rst]
set_property PACKAGE_PIN T18 [get_ports clk]
set_property PACKAGE_PIN A18 [get_ports btn_out]

set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports st]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports btn_out]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
